---
title: "HuanHusted_TSA_Competition"
author: "Kelsey Husted"
date: "2023-03-31"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), tidy=FALSE) 
```

##Load packages

```{r load packages, warning=FALSE, message=FALSE}
library(readxl)
library(dplyr)
library(lubridate)
library(openxlsx)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
```

## Wrangling and processing the data 2005-2009

Need to transform hourly data into daily data with aggregate and pipes.

```{r Wrangle & Process Data 2005-2009, message=FALSE, warning=FALSE}
#Import data
df <- read_xlsx("./Competition/Data/load.xlsx")

#Wrangle data from hourly to daily
#Wrangling date column 2005 to 2009
df_daily <- df %>%
  mutate( Date = ymd(date)) %>%
  filter(Date < '2010-01-01')

#removing no numeric columns so rowMeans() functino will work
df_dailyV2 <- df %>%
  mutate( Date = ymd(date)) %>%
  filter(Date < '2010-01-01') %>%
  select(3:26)

#Creating daily data
df_processed <- df_dailyV2 %>%  
  mutate(rowMeans(df_dailyV2)) %>%
  rename(Daily_data = "rowMeans(df_dailyV2)") %>%
  select(25)

#Combining data and daily data
date <- df_daily[,2]
df_processed <- cbind(date, df_processed)
         
```

## Wrangling and processing the data 2005-2010

```{r Wrangle & Process Data 2005-2010, message=FALSE, warning=FALSE}

#Wrangle data from hourly to daily
#Wrangling date column 2005 to 2010
#removing no numeric columns so rowMeans() functino will work
df_daily2010 <- df %>%
  mutate( Date = ymd(date)) %>%
  select(3:26)

#Creating daily data
df_processed2010 <- df_daily2010 %>%  
  mutate(rowMeans(df_daily2010)) %>%
  rename(Daily_data = "rowMeans(df_daily2010)") %>%
  select(25)

#Combining data and daily data
date <- df_daily2010[,2]
df_processed2010 <- cbind(date, df_processed2010)
         
```

## Create a time series object

```{r ts, message=FALSE, warning=FALSE}
#ts transformation 2005 to 2009
ts_daily <- msts(df_processed$Daily_data,
                 seasonal.periods=c(7,365.25),
                 start=c(2005, 01, 01))

#ts transformation 2005 to 2010
ts_daily2010 <- msts(df_processed2010$Daily_data,
                 seasonal.periods=c(7,365.25),
                 start=c(2005, 01, 01))
```

## Decompose time series

```{r Decompose, message=FALSE, warning=FALSE}

#Decompose time series 
ts_decompose <- ts_daily %>%
  mstl()
plot(ts_decompose)

```
## Model 1 STL: Forecast 2010

```{r Model 1, message=FALSE, warning=FALSE}
#Fit and forecast STL model 
ETS_model <-  stlf(ts_daily,h=365)

#Plot foresting
autoplot(ETS_model) + ylab("Forecast")

#Plot model + observed data
autoplot(ts_daily2010) +
  autolayer(ETS_model, series="STL Model",PI=FALSE) +
  ylab("Daily Data")
```

## Model 1 STL: Forecast 2011
```{r Model 1, message=FALSE, warning=FALSE}
#Fit and forecast STL model January 1st to February 28th 2011
ETS_model2011 <-  stlf(ts_daily2010,h=59)

#Plot foresting
autoplot(ETS_model2011) + ylab("Forecast")

#Plot model + observed data
autoplot(ts_daily2010) +
  autolayer(ETS_model2011, series="STL Model",PI=FALSE) +
  ylab("Daily Data")
```

## Model 2 TBATS: Forecast 2010

```{r Model 2, message=FALSE, warning=FALSE}
#Fit and forecast TBATS model 
TBATS_model <-  tbats(ts_daily)

#forecast
TBATS_for <- forecast(TBATS_model,h=356)

#Plot foresting
autoplot(TBATS_model) + ylab("Forecast")

#Plot model + observed data
autoplot(ts_daily2010) +
  autolayer(TBATS_for, series="TBATS Model",PI=FALSE) +
  ylab("Daily Data")
```
# This model looks like a bad fit so I won't forecast for 2011.

